pub mod status_route;
pub mod release_route;
pub mod cydia_icon_route;
pub mod root_route;
pub mod packages_route;
pub mod download_route;
pub mod packages_bz2_route;
pub mod sileo_featured_route;
pub mod sileo_depiction_route;